import { createFileRoute, Link } from "@tanstack/react-router";
import { useSuspenseQuery } from "@tanstack/react-query";
import { motion } from "motion/react";
import {
  Bot,
  Clock3,
  FileStack,
  Gauge,
  ArrowRight,
  GitBranch,
  ShieldCheck,
  Target,
  Wrench,
} from "lucide-react";
import { PageContainer, PageHeader } from "@/components/layout/PageContainer";
import { MetricCard } from "@/components/common/MetricCard";
import { SeverityBadge } from "@/components/common/SeverityBadge";
import { TimelineList } from "@/components/investigation/TimelineList";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { api, queryKeys } from "@/services/api";

export const Route = createFileRoute("/incident")({
  head: () => ({
    meta: [
      { title: "Incident Overview — ThreatVision AI" },
      {
        name: "description",
        content:
          "Risk score, blast radius, malware attribution and MITRE ATT&CK mapping for the active incident.",
      },
      { property: "og:title", content: "Incident Overview — ThreatVision AI" },
      {
        property: "og:description",
        content: "Executive view of a confirmed phishing-to-exfiltration intrusion.",
      },
    ],
  }),
  loader: async ({ context }) => {
    await Promise.all([
      context.queryClient.ensureQueryData({
        queryKey: queryKeys.latestAnalysis,
        queryFn: api.getLatestAnalysis,
      }),
      context.queryClient.ensureQueryData({
        queryKey: queryKeys.overview,
        queryFn: api.getIncidentOverview,
      }),
      context.queryClient.ensureQueryData({
        queryKey: queryKeys.timeline,
        queryFn: api.getTimeline,
      }),
    ]);
  },
  component: IncidentPage,
});

function IncidentPage() {
  const { data: analysis } = useSuspenseQuery({
    queryKey: queryKeys.latestAnalysis,
    queryFn: api.getLatestAnalysis,
  });
  const { data: overview } = useSuspenseQuery({
    queryKey: queryKeys.overview,
    queryFn: api.getIncidentOverview,
  });
  const { data: events } = useSuspenseQuery({
    queryKey: queryKeys.timeline,
    queryFn: api.getTimeline,
  });
  const isSafe = (analysis?.attackCategory ?? "").toLowerCase() === "safe";

  return (
    <PageContainer>
      <PageHeader
        eyebrow="Step 3 of 3"
        title={
          analysis ? (isSafe ? "No attack detected" : analysis.attackCategory) : "Incident Overview"
        }
        description={overview.summary}
        actions={
          <>
            <SeverityBadge severity={overview.severity} size="lg" />
            <Button asChild>
              <Link to="/reports">
                Open Report <ArrowRight className="size-4" />
              </Link>
            </Button>
          </>
        }
      />

      <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">
        <MetricCard
          label="Severity Score"
          value={`${overview.riskScore}/100`}
          hint="0 means safe"
          icon={Gauge}
          tone={isSafe ? "success" : "critical"}
          index={0}
        />
        <MetricCard
          label="Attack Category"
          value={analysis?.attackCategory ?? overview.malwareFamily}
          hint="Evidence based"
          icon={Target}
          tone={isSafe ? "success" : "warning"}
          index={1}
        />
        <MetricCard
          label="Intent"
          value={analysis?.probableIntent ?? "Pending"}
          hint="Safe if unsupported"
          icon={Bot}
          tone={isSafe ? "success" : "info"}
          index={2}
        />
        <MetricCard
          label="Damage Done"
          value={analysis?.damageDone ?? "Pending"}
          hint="No assumptions"
          icon={Wrench}
          tone={isSafe ? "success" : "warning"}
          index={3}
        />
        <MetricCard
          label="Timeline Events"
          value={overview.evidenceCount}
          hint="Supporting entries only"
          icon={FileStack}
          index={4}
        />
        <MetricCard
          label="Attack Window"
          value={overview.attackDuration}
          hint="From uploaded timestamps"
          icon={Clock3}
          tone="info"
          index={5}
        />
        <MetricCard
          label="Flowchart Nodes"
          value={analysis?.flowchart.nodes.length ?? 0}
          hint={isSafe ? "Empty for safe logs" : "Generated by Kimi"}
          icon={GitBranch}
          tone={isSafe ? "success" : "info"}
          index={6}
        />
        <MetricCard
          label="Status"
          value={isSafe ? "Safe" : "Review"}
          hint="Analyst validation recommended"
          icon={ShieldCheck}
          tone={isSafe ? "success" : "warning"}
          index={7}
        />
      </div>

      <div className="mt-6 grid gap-6 xl:grid-cols-[1.15fr_1fr]">
        <Card>
          <CardHeader className="space-y-1">
            <CardTitle className="text-base">Kimi analysis</CardTitle>
            <p className="text-sm text-muted-foreground">
              The backend only reports an attack when the uploaded logs provide concrete evidence.
            </p>
          </CardHeader>
          <CardContent className="grid gap-3 sm:grid-cols-3">
            {[
              ["Severity score", `${analysis?.severityScore ?? overview.riskScore}/100`],
              ["Attack category", analysis?.attackCategory ?? "Pending"],
              ["Probable intent", analysis?.probableIntent ?? "Pending"],
              ["Damage done", analysis?.damageDone ?? "Pending"],
              ["Timeline entries", String(events.length)],
              ["Flowchart steps", String(analysis?.flowchart.nodes.length ?? 0)],
            ].map(([label, value], i) => (
              <motion.div
                key={label}
                initial={{ opacity: 0, y: 8 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: i * 0.04 }}
                className="rounded-xl border bg-card p-4"
              >
                <p className="text-[11px] uppercase tracking-wide text-muted-foreground">{label}</p>
                <p className="mt-2 break-words text-sm font-semibold">{value}</p>
              </motion.div>
            ))}
          </CardContent>
        </Card>

        <Card>
          <CardHeader className="flex-row items-center justify-between space-y-0">
            <CardTitle className="text-base">Attack chronology</CardTitle>
            <Button variant="ghost" size="sm" asChild>
              <Link to="/timeline">Full timeline</Link>
            </Button>
          </CardHeader>
          <CardContent>
            {events.length > 0 ? (
              <TimelineList events={events} />
            ) : (
              <p className="rounded-xl border bg-success/10 p-4 text-sm text-muted-foreground">
                No attack timeline was produced because the uploaded logs were assessed as safe.
              </p>
            )}
          </CardContent>
        </Card>
      </div>
    </PageContainer>
  );
}
